### ISSUE TITLE
[회원] : 회원가입 기능 구현

### ISSUE THREAD

**Issue by ji-hyeon97** [EnjoyTripKorea/EnjoyTripBackend#1]
## 어떤 기능인가요?

> 회원가입 기능을 구현한다.
## ✏️  작업 상세 내용

- [x] 아이디 중복검사를 구현합니다.
- [x] 비밀번호는 단방향 알고리즘(SHA256 + salt) 로 구현합니다.
- [x] 회원 가입시 유효성 검사를 진행합니다.

**Comment by DebbieIsFree** [comment]
안녕하세요 페어님,
단순한 회원가입 구현에서 벗어나 
비밀번호에 알고리즘을 적용하신 점이 굉장히 좋다고 생각듭니다
수고하셨습니다.  :)
